name: 'Run tests'

on:
  push:
    branches:
      - 'coverage'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run tests with coverage
        run: npm run test:coverage
