name: 'Run tests and deploy'

on:
  push:
    branches:
      - 'main'
      - 'coverage'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run tests with coverage
        run: npm run test:coverage

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Simulate deployment
        run: echo "Deploying to production... (Simulated)"
