name: 'Run tests and deploy'

on:
  push:
    branches:
      - 'main'
      - 'coverage'
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run tests with coverage
        run: npm run test:coverage
      - name: Check coverage threshold
        run: |
          COVERAGE=$(npm run coverage | grep "All files" | awk '{print $5}' | tr -d '%')
          echo "Current coverage is $COVERAGE%"
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Coverage ($COVERAGE%) is below 70%"
            exit 1
          else
            echo "Coverage check passed!"
          fi
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Simulate deployment
        run: echo "Deploying to production... (Simulated)"
